import { spfOne, spfTwo, spfThree, spfFour } from "../assets/images";

export const LAUNCHES = [
  {
    id: 1,
    productName: "Knit Lite Slip Ons : Light Pink",
    image: spfOne,
    price: 2499,
    specialPrice: 1999,
    discount: null,
    rating: 4.5,
    reviewCount: 45,
    quantity: 10,
    description: "Slip-on sneaker in a lightweight knit fabric. Perfect for casual outings and daily wear. Breathable and comfortable.",
    colors: [
      { label: "Light Pink", hex: "#f4a7a7" },
      { label: "Black", hex: "#1f1f1f" },
      { label: "Olive", hex: "#6b7c4b" },
      { label: "Tan", hex: "#c9a87c" },
    ],
  },
  {
    id: 2,
    productName: "The Urban Riffs For Men : Red",
    image: spfTwo,
    price: 4599,
    specialPrice: 2299,
    discount: 50,
    rating: 4.86,
    reviewCount: 21,
    quantity: 5,
    description: "Street-style sneakers with bold silhouette. Features a responsive sole and durable upper for urban adventures.",
    colors: [
      { label: "Red", hex: "#e33030" },
      { label: "Blue", hex: "#4b6cb7" },
      { label: "White", hex: "#f0f0f0" },
      { label: "Black", hex: "#1f1f1f" },
    ],
  },
  {
    id: 3,
    productName: "Knit Gliders For Men : Beige",
    image: spfThree,
    price: 2499,
    specialPrice: 1899,
    discount: 24,
    rating: 4.75,
    reviewCount: 152,
    quantity: 8,
    description: "Breathable knit glider shoes for all-day comfort. Lightweight design with superior grip and support.",
    colors: [
      { label: "Beige", hex: "#d0b896" },
      { label: "White", hex: "#f0f0f0" },
      { label: "Grey", hex: "#9e9e9e" },
      { label: "Black", hex: "#1f1f1f" },
    ],
  },
  {
    id: 4,
    productName: "Cushers Clogs For Men : Pepper Green",
    image: spfFour,
    price: 1999,
    specialPrice: 999,
    discount: 50,
    rating: 4.79,
    reviewCount: 107,
    quantity: 3,
    description: "Croc-style clogs with cushioned insole for comfort. Ideal for beach, garden, or quick errands.",
    colors: [
      { label: "Pepper Green", hex: "#2e7d5e" },
      { label: "Sand", hex: "#c9a87c" },
      { label: "Orange", hex: "#e07a3b" },
      { label: "Yellow", hex: "#e8c44a" },
    ],
  },

];
